ApartamentS/Models/Ad.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ApartamentS.Models
{
    public class Ad
    {
        [Key]
        public int Id { get; set; }

        public int Author_Id { get; set; }

        public string Author_Name { get; set; }

        public DateTime DataCreat { get; set; }

        [Required(ErrorMessage = "Please type correct Title")]
        public string Title { get; set; }

        public string Description { get; set; }

        public string Address { get; set; }

        [Required(ErrorMessage = "Please type correct Phone")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Please type correct Price")]
        public int Price { get; set; }
        
    }
}

ApartamentS/Controllers/AdController.cs
using ApartamentS.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;

namespace ApartamentS.Controllers
{
    public class AdController : Controller
    {
        Models.ApartamentsContext db = new Models.ApartamentsContext();

        public ActionResult Ads()
        {
            string find;
            IQueryable<Ad> _Ads = db.Ads;
            if ((find = this.Request.QueryString["Title"]) != null)
            {
                Ad _ads = new Ad();
                ViewBag.ads = LuceneSearch.Search(find);
            }
            else
            {
                ViewBag.ads = _Ads;
            }
            return View();
        }

        public ActionResult Find(Ad _ad)
        {
            return RedirectToAction("Ads", new { Title = _ad.Title});
        }
        [HttpGet]
        [Authorize]
        public ActionResult add_Ad()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult add_Ad(Ad _ad, Picture _picture, IEnumerable<HttpPostedFileBase> upload)
        {
            if (ModelState.IsValid)
            {
                using (ApartamentsContext db = new ApartamentsContext())
                {
                    _ad.Author_Name = User.Identity.Name;

                    var auth_user = db.Users.Single(u => u.Login == _ad.Author_Name);

                    _ad.Author_Id = auth_user.Id;

                    foreach (HttpPostedFileBase picture in upload)
                    {
                        if (picture != null)
                        {
                            var path = Path.Combine(Server.MapPath("~/Images/"), picture.FileName); //файл
                            picture.SaveAs(path);
                            _picture.Picture_Path = "/Images/" + picture.FileName; // путь к файлу в базу - его имя
                            _picture.Id_ad = (int)db.Ads.LongCount() + 14 ;
                            db.Pictures.Add(_picture);
                            db.SaveChanges();

                        }
                    }

                    _ad.DataCreat = DateTime.Now;
                    // добавляем информацию о покупке в базу данных
                    db.Ads.Add(_ad);
                    // сохраняем в бд все изменения
                    db.SaveChanges();

                    LuceneSearch.AddUpdateLuceneIndex(AdRepository.GetAll());

                    return RedirectToAction("Ads");
                }
            }
            return View();
        }
    }
}

ApartamentS/Views/Ad/Ads.cshtml
@model ApartamentS.Models.Ad
@{
    Layout = null;
    Html.RenderPartial("Header");
}
<title>Ads</title>
<div id="templatemo_wrapper">
    @{
        int test = 0;
        foreach (var bag in ViewBag.ads)
        {
            test = 1;
            <hr>
            <div style="display: inline-block">
                <p>ID: @bag.Id</p>
                <p>Title: @bag.Title</p>
                @if (bag.Description != null)
                {
                    <p>Description: @bag.Description</p>
                }
                <p>
                    Author: @bag.Author_Name
                    @if (bag.Address != null)
                    {
                        <u>Address: @bag.Address</u>
                    }
                    Phone: @bag.Phone Price: @bag.Price ₽ DateCreat: @bag.DataCreat
                </p>
            </div>
            <div style="display: inline-block">
                @{
                    using (ApartamentS.Models.ApartamentsContext db = new ApartamentS.Models.ApartamentsContext())
                    {
                        foreach (ApartamentS.Models.Picture picture in db.Pictures)
                        {
                            if (bag.Id == picture.Id_ad)
                            {
                                <img src="@picture.Picture_Path" height="150" width="150">
                            }
                        }
                    }
                }
            </div>
        }
        if (test == 0)
        {
            <p>No such an ads</p>
        }
    }
</div>

ApartamentS/Views/Ad/add_Ad.cshtml
@model ApartamentS.Models.Ad
@{
    Layout = null;
    Html.RenderPartial("Header");
}
<title>add_Ad</title>
<div id="templatemo_wrapper">
    @using (Html.BeginForm("add_Ad", "Ad", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary()
        <p>Title: @Html.TextBoxFor(model => model.Title)</p>
        <p>Decription: @Html.TextBoxFor(model => model.Description)</p>
        <p>Address: @Html.TextBoxFor(model => model.Address)</p>
        <p>Phone: @Html.TextBoxFor(model => model.Phone)</p>
        <p>Price: @Html.TextBoxFor(model => model.Price)</p>
        <input type="file" name="upload" />
        <input type="file" name="upload" />
        <input type="file" name="upload" />
        <input type="submit" value="Create Ad" />
    }
</div>